// AUTO-GENERATED by vite.config.js — do not edit manually.
// Re-generated on every dev server start and production build.
// To add a new asset: create the file in blocks/ or pages/; restart dev server.

// ── Global styles ─────────────────────────────────────────────────────────
import '/styles/fonts.css';
import '/styles/reset.css';
import '/styles/variables.css';
import '/styles/typography.css';
import '/styles/globals.scss';

// ── Third-party ───────────────────────────────────────────────────────────
import 'lite-youtube-embed';
import 'lite-youtube-embed/src/lite-yt-embed.css';

// ── Blocks ────────────────────────────────────────────────────────────────
import '/blocks/about/about.scss';
import '/blocks/about-course/about-course.scss';
import '/blocks/autobiography/autobiography.scss';
import '/blocks/autobiography/autobiography.js';
import '/blocks/basic-course/basic-course.scss';
import '/blocks/bio/bio.scss';
import '/blocks/bottom-nav/bottom-nav.scss';
import '/blocks/bottom-nav/bottom-nav.js';
import '/blocks/breadcrumbs/breadcrumbs.scss';
import '/blocks/button/button.css';
import '/blocks/cartoon/cartoon.scss';
import '/blocks/chanel-subscribe/chanel-subscribe.scss';
import '/blocks/course-program/course-program.scss';
import '/blocks/course-program/course-program.js';
import '/blocks/course-schedule/course-schedule.scss';
import '/blocks/cta/cta.scss';
import '/blocks/cta/cta.js';
import '/blocks/cta-course/cta-course.scss';
import '/blocks/devider/devider.scss';
import '/blocks/event-card/event-card.scss';
import '/blocks/faq/faq.scss';
import '/blocks/footer/footer.scss';
import '/blocks/form/form.scss';
import '/blocks/form/form.js';
import '/blocks/form-field/form-field.scss';
import '/blocks/gallery/gallery.scss';
import '/blocks/gallery/gallery.js';
import '/blocks/header/header.scss';
import '/blocks/header/header.js';
import '/blocks/hero/hero.scss';
import '/blocks/how-it-works/how-it-works.scss';
import '/blocks/input/input.scss';
import '/blocks/intro/intro.scss';
import '/blocks/label-link/label-link.scss';
import '/blocks/lecture-card/lecture-card.scss';
import '/blocks/lectures/lectures.scss';
import '/blocks/lectures/lectures.js';
import '/blocks/lectures-list/lectures-list.scss';
import '/blocks/logo/logo.css';
import '/blocks/main-vector/main-vector.scss';
import '/blocks/my-approach/my-approach.scss';
import '/blocks/my-way/my-way.scss';
import '/blocks/my-way/my-way.js';
import '/blocks/mystery/mystery.scss';
import '/blocks/pages/pages.scss';
import '/blocks/personal-work/personal-work.scss';
import '/blocks/podcasts/podcasts.scss';
import '/blocks/practices/practices.scss';
import '/blocks/question/question.scss';
import '/blocks/question/question.js';
import '/blocks/schedule/schedule.scss';
import '/blocks/schedule/schedule.js';
import '/blocks/select/select.scss';
import '/blocks/select/select.js';
import '/blocks/seminar/seminar.scss';
import '/blocks/seminar-about/seminar-about.scss';
import '/blocks/smotrim/smotrim.scss';
import '/blocks/smotrim/smotrim.js';
import '/blocks/textarea/textarea.scss';
import '/blocks/trainings/trainings.scss';
import '/blocks/travelling/travelling.scss';
import '/blocks/travelling/travelling.js';
import '/blocks/video-card/video-card.scss';
import '/blocks/video-course/video-course.scss';
import '/blocks/videos/videos.scss';

// ── Pages ─────────────────────────────────────────────────────────────────
import '/pages/404/404.scss';
import '/pages/404/404.js';
import '/pages/about/about.scss';
import '/pages/about/about.js';
import '/pages/basic-course/basic-course.scss';
import '/pages/basic-course/basic-course.js';
import '/pages/main/main.css';
import '/pages/main/main.js';
import '/pages/master-course/master-course.scss';
import '/pages/master-course/master-course.js';
import '/pages/mystery/mystery.scss';
import '/pages/mystery/mystery.js';
import '/pages/philosophy/philosophy.scss';
import '/pages/philosophy/philosophy.js';
import '/pages/psychology/psychology.scss';
import '/pages/psychology/psychology.js';
import '/pages/schedule/schedule.scss';
import '/pages/schedule/schedule.js';
import '/pages/seminar/seminar.scss';
import '/pages/seminar/seminar.js';
import '/pages/trainings/trainings.scss';
import '/pages/trainings/trainings.js';
import '/pages/ui/ui.css';
